### ISSUE TITLE
Upstream changes?

### ISSUE THREAD

**Issue by rockymeza** [CptMonac/python-wifi#1]
Hi @CptMonac,

Any interest in making a pull-request for the wifi library?  I'm sure other people could benefit from your changes.

I don't have a PEAP wifi network available to me to test against this, but if it works for you I don't see why it wouldn't work for other people.

**Comment by CptMonac** [comment]
HI Rocky,
  You pretty much hit the issue right on the nail. I was not able to completely test the changes on the PEAP network i had access to and will not be back in the university for another couple months. I'll keep you posted on any updates though.
